apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: cron-send-notification
spec:
  type: bindings.cron
  version: v1
  metadata:
    - name: route
      value: /dapr/cron/send-notification
    - name: schedule
      value: "@every 10s"