apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: subscription-service-b
spec:
  pubsubname: message-broker
  topic: service-b
  routes:
    rules:
      - match: event.type == "OperationEMessage"
        path: /dapr/subscriptions/operation-e
      - match: event.type == "OperationFMessage"
        path: /dapr/subscriptions/operation-f
  metadata:
    routingKey: OperationEMessage,OperationFMessage