apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: message-broker
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
    - name: connectionString
      value: amqp://localhost:5672
    - name: durable
      value: true
    - name: deletedWhenUnused
      value: false